# Generated by Django 4.1.7 on 2023-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0002_jobsmodel_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(default='مدیریت', max_length=150)),
                ('melicod', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
