# Generated by Django 4.1.7 on 2023-06-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0003_employeemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servic', models.CharField(default='', max_length=150)),
                ('emp', models.CharField(default='', max_length=150)),
                ('time', models.CharField(default='', max_length=150)),
                ('cast', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
