# Generated by Django 4.1.7 on 2023-06-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0004_servicmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='servicmodel',
        ),
    ]
