# Generated by Django 4.1.7 on 2023-07-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0005_delete_servicmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='workmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(default='تزریقات', max_length=150)),
                ('cast', models.CharField(default='0', max_length=150)),
            ],
        ),
    ]
