# Generated by Django 4.1.7 on 2023-07-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0007_workmodel_person_workmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='detalework',
            field=models.CharField(default='تزریقات', max_length=150),
        ),
    ]
