# Generated by Django 4.1.7 on 2023-04-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuntmodel',
            name='berthday',
            field=models.CharField(max_length=100),
        ),
    ]
