# Generated by Django 4.1.7 on 2023-05-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0003_savecodphon_expaiercode_alter_accuntmodel_melicode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuntmodel',
            name='level',
            field=models.CharField(default='دسترسی معمولی', max_length=50),
        ),
    ]
