# Generated by Django 4.1.7 on 2023-07-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobreserv', models.CharField(default='m', max_length=150)),
                ('detalereserv', models.CharField(default='m', max_length=150)),
                ('personreserv', models.CharField(default='m', max_length=150)),
                ('timereserv', models.CharField(default='m', max_length=150)),
                ('castreserv', models.CharField(default='m', max_length=150)),
                ('dateshamsireserv', models.CharField(default='m', max_length=150)),
                ('datemiladireserv', models.CharField(default='m', max_length=150)),
            ],
        ),
    ]
