# Generated by Django 4.1.7 on 2023-07-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='yearshamsi',
            field=models.CharField(default='m', max_length=10),
        ),
    ]
