# Generated by Django 4.1.7 on 2023-07-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0002_reservemodel_yearshamsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='hourreserv',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservemodel',
            name='castreserv',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='reservemodel',
            name='datemiladireserv',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='reservemodel',
            name='dateshamsireserv',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='reservemodel',
            name='detalereserv',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='reservemodel',
            name='jobreserv',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='reservemodel',
            name='personreserv',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='reservemodel',
            name='timereserv',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='reservemodel',
            name='yearshamsi',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
