# Generated by Django 4.1.7 on 2023-07-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0003_reservemodel_hourreserv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='leavemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateshamsi', models.CharField(default='0', max_length=50)),
                ('datemiladi', models.CharField(default='0', max_length=50)),
                ('leave', models.CharField(default='0', max_length=630)),
            ],
        ),
    ]
