# Generated by Django 4.1.7 on 2023-07-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0005_leavemodel_personelmelicod'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='muont',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
