# Generated by Django 4.1.7 on 2023-09-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0006_leavemodel_muont'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservemodeltest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobreserv', models.CharField(default='0', max_length=150)),
                ('detalereserv', models.CharField(default='0', max_length=150)),
                ('personreserv', models.CharField(default='0', max_length=150)),
                ('timereserv', models.CharField(default='0', max_length=150)),
                ('castreserv', models.CharField(default='0', max_length=150)),
                ('hourreserv', models.CharField(default='0', max_length=10)),
                ('dateshamsireserv', models.CharField(default='0', max_length=150)),
                ('datemiladireserv', models.CharField(default='0', max_length=150)),
                ('yearshamsi', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
