# Generated by Django 4.1.7 on 2023-09-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0009_reservemodel_pyment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodeltest',
            name='mellicode',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
