# Generated by Django 4.1.7 on 2023-09-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0011_reservemodel_bank_reservemodel_melicod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neursemodel',
            old_name='image_full',
            new_name='image_show',
        ),
        migrations.RenameField(
            model_name='neursetestmodel',
            old_name='image_full',
            new_name='image_show',
        ),
        migrations.RemoveField(
            model_name='neursemodel',
            name='image_not',
        ),
        migrations.RemoveField(
            model_name='neursemodel',
            name='image_semi',
        ),
        migrations.RemoveField(
            model_name='neursetestmodel',
            name='image_not',
        ),
        migrations.RemoveField(
            model_name='neursetestmodel',
            name='image_semi',
        ),
    ]
