# Generated by Django 4.1.7 on 2023-09-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_app', '0012_rename_image_full_neursemodel_image_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='numbertime',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='reservemodeltest',
            name='numbertime',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
